# Generated by Django 2.1.7 on 2019-03-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('hobby', models.CharField(max_length=20)),
                ('constellation', models.CharField(max_length=20)),
            ],
        ),
    ]
